### ISSUE TITLE
gateway mac

### ISSUE THREAD

**Issue by FirePoleR** [flashnuke/ArpWarp#4]
```

      ____                 _ _   _      _
     |  _ \  ___  ____  __| | \ | | ___| |_
     | | | |/ _ \/ _  |/ _` |  \| |/ _ \ __|
     | |_| |  __/ (_| | (_| | |\  |  __/ |_
     |____/ \___|\__,_|\__,_|_| \_|\___|\__|

Written by @flashnuke
=================================================
Traceback (most recent call last):
  File "/mnt/c/Program Files/Ovnia/deadnet/./deadnet.py", line 173, in <module>
    attacker = DeadNet(arguments.iface, arguments.cidrlen, arguments.s_time, arguments.gateway,
  File "/mnt/c/Program Files/Ovnia/deadnet/./deadnet.py", line 42, in __init__
    raise Exception(f"{RED}[-]{WHITE} Unable to get gateway mac -> {self.gateway_ipv4}")
Exception: [-] Unable to get gateway mac -> x.x.x.1
```

help need some guidance

**Comment by flashnuke** [comment]
What is the command you're running? Have you tried passing an interface using the `-i` arg?

**Comment by FirePoleR** [comment]
i'm running this ```./deadnet.py -i eth0```, I also tried setting the gateway manually but still gives me the same output

**Comment by flashnuke** [comment]
I created this branch with an alternative way to get the gateway MAC address https://github.com/flashnuke/deadnet/tree/test/gateway_mac

* please clone it let me know if it works so I can merge it

* if it doesnt work, i'd like to know what command you used (the full one) when you passed the gateway ipv4 manually + the output of `ifconfig`
* also, what OS are you using?

thanks!

**Comment by flashnuke** [comment]
this should address the issue https://github.com/flashnuke/deadnet/pull/5
